version: "3.8"

services:
  server:
    image: chatterserver
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: dechat
      POSTGRES_USER: dechat
      POSTGRES_DB: dechat
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
